# Generated by Django 5.1.6 on 2025-04-01 13:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='crop',
            old_name='added_on',
            new_name='date_added',
        ),
        migrations.RenameField(
            model_name='crop',
            old_name='item_name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='inventory',
            name='transaction_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='crop',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='crop',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='crops', to=settings.AUTH_USER_MODEL),
        ),
    ]
